console.log('############# Teresópois, 23 de Março de 2021 #############')
console.log('Olá')
console.log('Não sou seu primeiro código em JS mas sou um dos primeiros no curso do SerraTec.')
console.log('Bem vindo nessa jornada, vamos evoluir bastante nos próximos meses.')
console.log('Boa sorte e bons estudos')