const alunos = [
    'Alice Períles Machado',
    'Amanda Melo Silva',
    'André Ricardo Adami Drummond Filho',
    'Bernard Muniz Rebello',
    'Daniel Bevilacqua Da Mata Pereira',
    'Emerson De Mello Ramos',
    'Erich Kenupp Ulrichsen Marcelino',
    'Everton Da Silva Macedo',
    'Gabriela Medeiros Prizo',
    'Gabriel Gaspar Esteves',
    'Giovanne Menezes Lopes',
    'Giulia Do Nascimento',
    'Gustavo de Almeida Machado Trigo',
    'Israel Da Roza Borges',
    'Jennyffer Brandão Da Silva Santos',
    'Jéssica Sampaio Pereira',
    'João Victor De Melo Justino',
    'Karine Branco',
    'Larissa De Oliveira Couto',
    'Leonardo Fernandes De Almeida',
    'Luana Tayt son Leal Ponte',
    'Luan Figueiredo Lopes',
    'Luiz Carlos Almeida Gama Junior',
    'Luiz Eduardo Moreira Da Costa',
    'Maicon De Oliveira',
    'Marcelo Renato Pinto Filgueira',
    'Mariana Camargo De Oliveira',
    'Maria Regina Lopes de Oliveira dos Santos',
    'Matheus Farias Corrêa',
    'Natan Melo De Oliveira',
    'Nicolly Silva Monteiro De Almeida',
    'Paulo Roberto De Andrade Maia Junior',
    'Raphael Rapozo Rebello De Rezende',
    'Sthephanie Soares Nogueira',
    'Taiana Monteiro Faria',
    'Werikson Rodrigues De Araújo',
    'William Pimentel Da Silva'
];
for (i = 0; i < alunos.length; i++){
    console.log(alunos[i].split(" ", 1));
}